// <auto-generated />
using System;
using F1_Fantasy_liga.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F1_Fantasy_liga.Migrations
{
    [DbContext(typeof(F1DbContext))]
    [Migration("20260611153338_addedConstructorImage")]
    partial class addedConstructorImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DriverFantasyTeam", b =>
                {
                    b.Property<int>("DriversId")
                        .HasColumnType("int");

                    b.Property<int>("FantasyTeamsId")
                        .HasColumnType("int");

                    b.HasKey("DriversId", "FantasyTeamsId");

                    b.HasIndex("FantasyTeamsId");

                    b.ToTable("FantasyTeamDrivers", (string)null);

                    b.HasData(
                        new
                        {
                            DriversId = 1,
                            FantasyTeamsId = 1
                        },
                        new
                        {
                            DriversId = 3,
                            FantasyTeamsId = 1
                        },
                        new
                        {
                            DriversId = 5,
                            FantasyTeamsId = 1
                        },
                        new
                        {
                            DriversId = 3,
                            FantasyTeamsId = 2
                        },
                        new
                        {
                            DriversId = 4,
                            FantasyTeamsId = 2
                        },
                        new
                        {
                            DriversId = 6,
                            FantasyTeamsId = 2
                        },
                        new
                        {
                            DriversId = 1,
                            FantasyTeamsId = 3
                        },
                        new
                        {
                            DriversId = 2,
                            FantasyTeamsId = 3
                        },
                        new
                        {
                            DriversId = 5,
                            FantasyTeamsId = 3
                        },
                        new
                        {
                            DriversId = 4,
                            FantasyTeamsId = 4
                        },
                        new
                        {
                            DriversId = 3,
                            FantasyTeamsId = 4
                        },
                        new
                        {
                            DriversId = 5,
                            FantasyTeamsId = 4
                        },
                        new
                        {
                            DriversId = 3,
                            FantasyTeamsId = 5
                        },
                        new
                        {
                            DriversId = 1,
                            FantasyTeamsId = 5
                        },
                        new
                        {
                            DriversId = 5,
                            FantasyTeamsId = 5
                        },
                        new
                        {
                            DriversId = 4,
                            FantasyTeamsId = 6
                        },
                        new
                        {
                            DriversId = 6,
                            FantasyTeamsId = 6
                        },
                        new
                        {
                            DriversId = 5,
                            FantasyTeamsId = 6
                        });
                });

            modelBuilder.Entity("F1_Fantasy_liga.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "31f14ee4-48de-4afc-bce5-3a0c91f8b596",
                            Email = "marko@email.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Marko",
                            NormalizedEmail = "MARKO@EMAIL.COM",
                            NormalizedUserName = "MARKO@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEI4c6/U5eyYk3JGdwKTbo/zv5eCrQglDBU882l19YeTiySb+TPRob4s0WFrzTM0Cxw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9303f7cc-2ccd-45b6-ac8a-017498652708",
                            Surname = "Horvat",
                            TwoFactorEnabled = false,
                            UserName = "marko@email.com"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c7ac7a69-f6d2-466c-952b-a44c9ffdd548",
                            Email = "ivana@email.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Ivana",
                            NormalizedEmail = "IVANA@EMAIL.COM",
                            NormalizedUserName = "IVANA@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBWiNCo9Sv3W7rwFL1Sta+SsnkRpZkh0pv9YFej3kL+2GHQn8GgQFhnRsSBPfKB5ZA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a19cf140-9b4a-49e6-beca-fd9769dbafe4",
                            Surname = "Zec",
                            TwoFactorEnabled = false,
                            UserName = "ivana@email.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "756a3965-ff48-474c-a3c2-d35850db2a16",
                            Email = "pero@email.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Pero",
                            NormalizedEmail = "PERO@EMAIL.COM",
                            NormalizedUserName = "PERO@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN/bcqO6wOuiHMRfiQwKD6JGqE23k5cSs0IDS+ZsbBAB4IVTfr7isa6Q52fIOdvVMg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "25cc56c4-ef32-4453-9644-62aaf0a94118",
                            Surname = "Kovač",
                            TwoFactorEnabled = false,
                            UserName = "pero@email.com"
                        });
                });

            modelBuilder.Entity("F1_Fantasy_liga.Models.Circuit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumberOfLaps")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Circuits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Sakhir",
                            Country = "Bahrain",
                            IsDeleted = false,
                            Length = 5.4119999999999999,
                            Name = "Bahrain International Circuit",
                            NumberOfLaps = 57
                        },
                        new
                        {
                            Id = 2,
                            City = "Monte Carlo",
                            Country = "Monaco",
                            IsDeleted = false,
                            Length = 3.3370000000000002,
                            Name = "Circuit de Monaco",
                            NumberOfLaps = 78
                        },
                        new
                        {
                            Id = 3,
                            City = "Monza",
                            Country = "Italy",
                            IsDeleted = false,
                            Length = 5.7930000000000001,
                            Name = "Autodromo Nazionale Monza",
                            NumberOfLaps = 53
                        });
                });

            modelBuilder.Entity("F1_Fantasy_liga.Models.Constructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FoundedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Constructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FoundedDate = new DateTime(2005, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "",
                            IsDeleted = false,
                            Name = "Red Bull Racing",
                            Nationality = "Austrian"
                        },
                        new
                        {
                            Id = 2,
                            FoundedDate = new DateTime(1950, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "",
                            IsDeleted = false,
                            Name = "Scuderia Ferrari",
                            Nationality = "Italian"
                        },
                        new
                        {
                            Id = 3,
                            FoundedDate = new DateTime(1954, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "",
                            IsDeleted = false,
                            Name = "Mercedes-AMG Petronas",
                            Nationality = "German"
                        },
                        new
                        {
                            Id = 4,
                            FoundedDate = new DateTime(1963, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "",
                            IsDeleted = false,
                            Name = "McLaren",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 5,
                            FoundedDate = new DateTime(2021, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "",
                            IsDeleted = false,
                            Name = "Aston Martin",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 6,
                            FoundedDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "",
                            IsDeleted = false,
                            Name = "Alpine",
                            Nationality = "French"
                        },
                        new
                        {
                            Id = 7,
                            FoundedDate = new DateTime(1977, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "",
                            IsDeleted = false,
                            Name = "Williams",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 8,
                            FoundedDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "",
                            IsDeleted = false,
                            Name = "Visa Cash App RB",
                            Nationality = "Italian"
                        },
                        new
                        {
                            Id = 9,
                            FoundedDate = new DateTime(1993, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "",
                            IsDeleted = false,
                            Name = "Kick Sauber",
                            Nationality = "Swiss"
                        },
                        new
                        {
                            Id = 10,
                            FoundedDate = new DateTime(2016, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagePath = "",
                            IsDeleted = false,
                            Name = "Haas F1 Team",
                            Nationality = "American"
                        });
                });

            modelBuilder.Entity("F1_Fantasy_liga.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstructorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConstructorId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConstructorId = 1,
                            IsDeleted = false,
                            Name = "Max",
                            Number = 1,
                            Price = 33.5m,
                            Surname = "Verstappen"
                        },
                        new
                        {
                            Id = 2,
                            ConstructorId = 1,
                            IsDeleted = false,
                            Name = "Sergio",
                            Number = 11,
                            Price = 18.0m,
                            Surname = "Perez"
                        },
                        new
                        {
                            Id = 3,
                            ConstructorId = 2,
                            IsDeleted = false,
                            Name = "Charles",
                            Number = 16,
                            Price = 26.5m,
                            Surname = "Leclerc"
                        },
                        new
                        {
                            Id = 4,
                            ConstructorId = 2,
                            IsDeleted = false,
                            Name = "Carlos",
                            Number = 55,
                            Price = 23.0m,
                            Surname = "Sainz"
                        },
                        new
                        {
                            Id = 5,
                            ConstructorId = 3,
                            IsDeleted = false,
                            Name = "Lewis",
                            Number = 44,
                            Price = 28.0m,
                            Surname = "Hamilton"
                        },
                        new
                        {
                            Id = 6,
                            ConstructorId = 3,
                            IsDeleted = false,
                            Name = "George",
                            Number = 63,
                            Price = 21.0m,
                            Surname = "Russell"
                        },
                        new
                        {
                            Id = 7,
                            ConstructorId = 4,
                            IsDeleted = false,
                            Name = "Lando",
                            Number = 4,
                            Price = 25.0m,
                            Surname = "Norris"
                        },
                        new
                        {
                            Id = 8,
                            ConstructorId = 4,
                            IsDeleted = false,
                            Name = "Oscar",
                            Number = 81,
                            Price = 21.5m,
                            Surname = "Piastri"
                        },
                        new
                        {
                            Id = 9,
                            ConstructorId = 5,
                            IsDeleted = false,
                            Name = "Fernando",
                            Number = 14,
                            Price = 24.0m,
                            Surname = "Alonso"
                        },
                        new
                        {
                            Id = 10,
                            ConstructorId = 5,
                            IsDeleted = false,
                            Name = "Lance",
                            Number = 18,
                            Price = 16.0m,
                            Surname = "Stroll"
                        },
                        new
                        {
                            Id = 11,
                            ConstructorId = 6,
                            IsDeleted = false,
                            Name = "Esteban",
                            Number = 31,
                            Price = 17.5m,
                            Surname = "Ocon"
                        },
                        new
                        {
                            Id = 12,
                            ConstructorId = 6,
                            IsDeleted = false,
                            Name = "Pierre",
                            Number = 10,
                            Price = 18.0m,
                            Surname = "Gasly"
                        },
                        new
                        {
                            Id = 13,
                            ConstructorId = 7,
                            IsDeleted = false,
                            Name = "Alexander",
                            Number = 23,
                            Price = 15.5m,
                            Surname = "Albon"
                        },
                        new
                        {
                            Id = 14,
                            ConstructorId = 7,
                            IsDeleted = false,
                            Name = "Logan",
                            Number = 2,
                            Price = 12.0m,
                            Surname = "Sargeant"
                        },
                        new
                        {
                            Id = 15,
                            ConstructorId = 8,
                            IsDeleted = false,
                            Name = "Yuki",
                            Number = 22,
                            Price = 17.0m,
                            Surname = "Tsunoda"
                        },
                        new
                        {
                            Id = 16,
                            ConstructorId = 8,
                            IsDeleted = false,
                            Name = "Daniel",
                            Number = 3,
                            Price = 18.5m,
                            Surname = "Ricciardo"
                        },
                        new
                        {
                            Id = 17,
                            ConstructorId = 9,
                            IsDeleted = false,
                            Name = "Valtteri",
                            Number = 77,
                            Price = 16.5m,
                            Surname = "Bottas"
                        },
                        new
                        {
                            Id = 18,
                            ConstructorId = 9,
                            IsDeleted = false,
                            Name = "Guanyu",
                            Number = 24,
                            Price = 15.0m,
                            Surname = "Zhou"
                        },
                        new
                        {
                            Id = 19,
                            ConstructorId = 10,
                            IsDeleted = false,
                            Name = "Kevin",
                            Number = 20,
                            Price = 15.5m,
                            Surname = "Magnussen"
                        },
                        new
                        {
                            Id = 20,
                            ConstructorId = 10,
                            IsDeleted = false,
                            Name = "Nico",
                            Number = 27,
                            Price = 16.0m,
                            Surname = "Hulkenberg"
                        });
                });

            modelBuilder.Entity("F1_Fantasy_liga.Models.FantasyLeague", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LeagueType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FantasyLeagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Privatna fantasy liga",
                            EndDate = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeagueType = 0,
                            Name = "Prijatelji Liga 2024",
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Otvorena liga za sve",
                            EndDate = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeagueType = 1,
                            Name = "Javna Liga 2024",
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Liga za napredne igrače",
                            EndDate = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeagueType = 0,
                            Name = "Elitna Liga 2024",
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("F1_Fantasy_liga.Models.FantasyTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ConstructorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FantasyLeagueId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ConstructorId");

                    b.HasIndex("FantasyLeagueId");

                    b.HasIndex("UserId");

                    b.ToTable("FantasyTeams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 88.5m,
                            ConstructorId = 2,
                            FantasyLeagueId = 1,
                            IsDeleted = false,
                            Name = "Speed Demons",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            Budget = 71.0m,
                            ConstructorId = 3,
                            FantasyLeagueId = 1,
                            IsDeleted = false,
                            Name = "Tifosi Forza",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 3,
                            Budget = 80.0m,
                            ConstructorId = 1,
                            FantasyLeagueId = 2,
                            IsDeleted = false,
                            Name = "Verstappen Fan Club",
                            UserId = "3"
                        },
                        new
                        {
                            Id = 4,
                            Budget = 88.5m,
                            ConstructorId = 2,
                            FantasyLeagueId = 3,
                            IsDeleted = false,
                            Name = "One Man Wolf Pack",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 5,
                            Budget = 71.0m,
                            ConstructorId = 3,
                            FantasyLeagueId = 3,
                            IsDeleted = false,
                            Name = "Forza England",
                            UserId = "2"
                        },
                        new
                        {
                            Id = 6,
                            Budget = 80.0m,
                            ConstructorId = 1,
                            FantasyLeagueId = 3,
                            IsDeleted = false,
                            Name = "LH44",
                            UserId = "3"
                        });
                });

            modelBuilder.Entity("F1_Fantasy_liga.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CircuitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RaceDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CircuitId");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CircuitId = 1,
                            IsDeleted = false,
                            Name = "Bahrain Grand Prix",
                            RaceDate = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CircuitId = 2,
                            IsDeleted = false,
                            Name = "Monaco Grand Prix",
                            RaceDate = new DateTime(2024, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CircuitId = 3,
                            IsDeleted = false,
                            Name = "Italian Grand Prix",
                            RaceDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("F1_Fantasy_liga.Models.RaceResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("DriverStatus")
                        .HasColumnType("int");

                    b.Property<int>("FinishedPosition")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("ScoredPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DriverId = 1,
                            DriverStatus = 0,
                            FinishedPosition = 1,
                            IsDeleted = false,
                            RaceId = 1,
                            ScoredPoints = 25
                        },
                        new
                        {
                            Id = 2,
                            DriverId = 4,
                            DriverStatus = 0,
                            FinishedPosition = 2,
                            IsDeleted = false,
                            RaceId = 1,
                            ScoredPoints = 18
                        },
                        new
                        {
                            Id = 3,
                            DriverId = 3,
                            DriverStatus = 0,
                            FinishedPosition = 3,
                            IsDeleted = false,
                            RaceId = 1,
                            ScoredPoints = 15
                        },
                        new
                        {
                            Id = 4,
                            DriverId = 5,
                            DriverStatus = 0,
                            FinishedPosition = 4,
                            IsDeleted = false,
                            RaceId = 1,
                            ScoredPoints = 12
                        },
                        new
                        {
                            Id = 5,
                            DriverId = 2,
                            DriverStatus = 2,
                            FinishedPosition = 0,
                            IsDeleted = false,
                            RaceId = 1,
                            ScoredPoints = 0
                        },
                        new
                        {
                            Id = 6,
                            DriverId = 3,
                            DriverStatus = 0,
                            FinishedPosition = 1,
                            IsDeleted = false,
                            RaceId = 2,
                            ScoredPoints = 25
                        },
                        new
                        {
                            Id = 7,
                            DriverId = 1,
                            DriverStatus = 0,
                            FinishedPosition = 2,
                            IsDeleted = false,
                            RaceId = 2,
                            ScoredPoints = 18
                        },
                        new
                        {
                            Id = 8,
                            DriverId = 5,
                            DriverStatus = 0,
                            FinishedPosition = 3,
                            IsDeleted = false,
                            RaceId = 2,
                            ScoredPoints = 15
                        },
                        new
                        {
                            Id = 9,
                            DriverId = 6,
                            DriverStatus = 3,
                            FinishedPosition = 0,
                            IsDeleted = false,
                            RaceId = 2,
                            ScoredPoints = 0
                        },
                        new
                        {
                            Id = 10,
                            DriverId = 3,
                            DriverStatus = 0,
                            FinishedPosition = 1,
                            IsDeleted = false,
                            RaceId = 3,
                            ScoredPoints = 25
                        },
                        new
                        {
                            Id = 11,
                            DriverId = 5,
                            DriverStatus = 0,
                            FinishedPosition = 2,
                            IsDeleted = false,
                            RaceId = 3,
                            ScoredPoints = 18
                        },
                        new
                        {
                            Id = 12,
                            DriverId = 6,
                            DriverStatus = 0,
                            FinishedPosition = 3,
                            IsDeleted = false,
                            RaceId = 3,
                            ScoredPoints = 15
                        },
                        new
                        {
                            Id = 13,
                            DriverId = 1,
                            DriverStatus = 2,
                            FinishedPosition = 0,
                            IsDeleted = false,
                            RaceId = 3,
                            ScoredPoints = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-user",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "role-admin"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "role-user"
                        },
                        new
                        {
                            UserId = "3",
                            RoleId = "role-user"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DriverFantasyTeam", b =>
                {
                    b.HasOne("F1_Fantasy_liga.Models.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriversId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("F1_Fantasy_liga.Models.FantasyTeam", null)
                        .WithMany()
                        .HasForeignKey("FantasyTeamsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("F1_Fantasy_liga.Models.Driver", b =>
                {
                    b.HasOne("F1_Fantasy_liga.Models.Constructor", "Constructor")
                        .WithMany("Drivers")
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constructor");
                });

            modelBuilder.Entity("F1_Fantasy_liga.Models.FantasyTeam", b =>
                {
                    b.HasOne("F1_Fantasy_liga.Models.Constructor", "Constructor")
                        .WithMany()
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1_Fantasy_liga.Models.FantasyLeague", "FantasyLeague")
                        .WithMany("FantasyTeams")
                        .HasForeignKey("FantasyLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1_Fantasy_liga.Models.AppUser", "User")
                        .WithMany("FantasyTeams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constructor");

                    b.Navigation("FantasyLeague");

                    b.Navigation("User");
                });

            modelBuilder.Entity("F1_Fantasy_liga.Models.Race", b =>
                {
                    b.HasOne("F1_Fantasy_liga.Models.Circuit", "Circuit")
                        .WithMany()
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circuit");
                });

            modelBuilder.Entity("F1_Fantasy_liga.Models.RaceResult", b =>
                {
                    b.HasOne("F1_Fantasy_liga.Models.Driver", "Driver")
                        .WithMany("RaceResults")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1_Fantasy_liga.Models.Race", "Race")
                        .WithMany("RaceResults")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("F1_Fantasy_liga.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("F1_Fantasy_liga.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1_Fantasy_liga.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("F1_Fantasy_liga.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1_Fantasy_liga.Models.AppUser", b =>
                {
                    b.Navigation("FantasyTeams");
                });

            modelBuilder.Entity("F1_Fantasy_liga.Models.Constructor", b =>
                {
                    b.Navigation("Drivers");
                });

            modelBuilder.Entity("F1_Fantasy_liga.Models.Driver", b =>
                {
                    b.Navigation("RaceResults");
                });

            modelBuilder.Entity("F1_Fantasy_liga.Models.FantasyLeague", b =>
                {
                    b.Navigation("FantasyTeams");
                });

            modelBuilder.Entity("F1_Fantasy_liga.Models.Race", b =>
                {
                    b.Navigation("RaceResults");
                });
#pragma warning restore 612, 618
        }
    }
}
